# Generated by Django 3.2.6 on 2023-02-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCategories', '0002_auto_20230201_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='frac',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchasing_unit',
            field=models.PositiveIntegerField(verbose_name='purchasing unit in pcs'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sales_unit',
            field=models.PositiveIntegerField(verbose_name='sales unit in pcs'),
        ),
    ]
