# Generated by Django 3.2.6 on 2023-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCategories', '0003_auto_20230201_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_barcode',
            field=models.CharField(max_length=15),
        ),
    ]
