# Generated by Django 3.2.6 on 2023-02-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemCategories', '0005_remove_products_item_barcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
